name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest

    env:
      Solution_Name: EasyFly.Web.sln
      Test_Project_Path: EasyFly.Tests/ServiceTests/*.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: ServiceTests
      run: dotnet test ServiceTests --configuration ${{ matrix.configuration }} --logger trx --results-directory ./TestResults
