name: CI
on: [push]

jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: Restore dependencies
        run: dotnet restore EasyFly.Web.sln

      - name: Build
        run: dotnet build EasyFly.Web.sln --configuration Release --no-restore

      - name: Publish
        run: |
          dotnet publish EasyFly.Web.sln \
            --configuration Release \
            --output ./publish \
            --runtime win-x86 \
            --no-build

      - name: Test
        run: dotnet test EasyFly.Web.sln --no-build --verbosity normal

      - name: Deploy to MonsterASP.NET via WebDeploy
        uses: rasmusbuchholdt/simply-web-deploy@2.1.0
        with:
          website-name: ${{ secrets.WEBSITE_NAME }}
          server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
          server-username: ${{ secrets.SERVER_USERNAME }}
          server-password: ${{ secrets.SERVER_PASSWORD }}
